"""initial core schema

Revision ID: f8b076d19b58
Revises: 
Create Date: 2026-08-30 18:34:55.370256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'f8b076d19b58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citation',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('source_text', sa.String(length=255), nullable=False),
    sa.Column('chapter', sa.String(length=255), nullable=True),
    sa.Column('verse', sa.String(length=100), nullable=True),
    sa.Column('quote_en', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citation_rule_id'), 'citation', ['rule_id'], unique=False)
    op.create_table('patient',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('health_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date().with_variant(sa.String(length=10), 'sqlite'), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('home_region', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.String(length=30), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_health_id'), 'patient', ['health_id'], unique=True)
    op.create_table('terminology',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('system', sa.String(length=15), nullable=False),
    sa.Column('term_en', sa.String(length=255), nullable=False),
    sa.Column('term_sa', sa.String(length=255), nullable=True),
    sa.Column('devanagari', sa.String(length=255), nullable=True),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.CheckConstraint("system IN ('namaste','who_tm2','internal')", name='ck_term_system'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terminology_code'), 'terminology', ['code'], unique=True)
    op.create_table('constitution_assessment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('assessed_on', sa.String(length=30), server_default='now()', nullable=False),
    sa.Column('vata_score', sa.Float(), nullable=False),
    sa.Column('pitta_score', sa.Float(), nullable=False),
    sa.Column('kapha_score', sa.Float(), nullable=False),
    sa.Column('derived_type', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('discrepancy_flag', sa.Boolean(), nullable=False),
    sa.CheckConstraint("derived_type IN ('vata','pitta','kapha','vata_pitta','pitta_kapha','vata_kapha','tridosha')", name='ck_constitution_type'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constitution_assessment_patient_id'), 'constitution_assessment', ['patient_id'], unique=False)
    op.create_table('visit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('visit_date', sa.String(length=30), server_default='now()', nullable=False),
    sa.Column('practitioner_id', sa.String(length=36), nullable=False),
    sa.Column('visit_type', sa.String(length=20), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), server_default='now()', nullable=False),
    sa.CheckConstraint("visit_type IN ('new', 'follow_up')", name='ck_visit_type'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_patient_id'), 'visit', ['patient_id'], unique=False)
    op.create_index(op.f('ix_visit_practitioner_id'), 'visit', ['practitioner_id'], unique=False)
    op.create_table('clinical_exam',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=False),
    sa.Column('pulse', sa.JSON(), nullable=True),
    sa.Column('urine', sa.JSON(), nullable=True),
    sa.Column('stool', sa.JSON(), nullable=True),
    sa.Column('tongue', sa.JSON(), nullable=True),
    sa.Column('voice', sa.JSON(), nullable=True),
    sa.Column('touch', sa.JSON(), nullable=True),
    sa.Column('eyes', sa.JSON(), nullable=True),
    sa.Column('appearance', sa.JSON(), nullable=True),
    sa.Column('agni', sa.String(length=15), nullable=True),
    sa.Column('koshtha', sa.String(length=10), nullable=True),
    sa.Column('ama_flag', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.String(length=30), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_exam_visit_id'), 'clinical_exam', ['visit_id'], unique=True)
    op.create_table('constitution_response',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('attribute', sa.String(length=100), nullable=False),
    sa.Column('option_chosen', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['constitution_assessment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constitution_response_assessment_id'), 'constitution_response', ['assessment_id'], unique=False)
    op.create_table('dictation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=False),
    sa.Column('audio_ref', sa.String(length=512), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('extractions', sa.JSON(), nullable=False),
    sa.Column('accepted', sa.JSON(), nullable=False),
    sa.Column('overridden', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=30), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictation_visit_id'), 'dictation', ['visit_id'], unique=False)
    op.create_table('disease_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=False),
    sa.Column('citation_id', sa.String(length=64), nullable=False),
    sa.Column('causes', sa.JSON(), nullable=False),
    sa.Column('early_signs', sa.JSON(), nullable=False),
    sa.Column('symptoms', sa.JSON(), nullable=False),
    sa.Column('relief_test_result', sa.Text(), nullable=True),
    sa.Column('process_notes', sa.Text(), nullable=True),
    sa.Column('progression_stage', sa.String(length=25), nullable=True),
    sa.Column('recorded_at', sa.String(length=30), server_default='now()', nullable=False),
    sa.CheckConstraint("progression_stage IS NULL OR progression_stage IN ('sanchaya','prakopa','prasara','sthana_samshraya','vyakti','bheda')", name='ck_da_progression_stage'),
    sa.ForeignKeyConstraint(['citation_id'], ['citation.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disease_analysis_visit_id'), 'disease_analysis', ['visit_id'], unique=True)
    op.create_table('finding_code',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=False),
    sa.Column('field_path', sa.String(length=255), nullable=False),
    sa.Column('national_code', sa.String(length=50), nullable=False),
    sa.Column('national_term', sa.String(length=255), nullable=False),
    sa.Column('who_tm_code', sa.String(length=50), nullable=False),
    sa.Column('who_bio_code', sa.String(length=50), nullable=True),
    sa.Column('coded_by', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(length=30), server_default='now()', nullable=False),
    sa.CheckConstraint("coded_by IN ('auto','manual')", name='ck_fc_coded_by'),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_code_national_code'), 'finding_code', ['national_code'], unique=False)
    op.create_index(op.f('ix_finding_code_visit_id'), 'finding_code', ['visit_id'], unique=False)
    op.create_index(op.f('ix_finding_code_who_tm_code'), 'finding_code', ['who_tm_code'], unique=False)
    op.create_table('imbalance_assessment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=False),
    sa.Column('vata_state', sa.String(length=15), nullable=False),
    sa.Column('pitta_state', sa.String(length=15), nullable=False),
    sa.Column('kapha_state', sa.String(length=15), nullable=False),
    sa.Column('dominant', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.String(length=30), server_default='now()', nullable=False),
    sa.CheckConstraint("dominant IN ('vata','pitta','kapha','vata_pitta','pitta_kapha','vata_kapha','tridosha')", name='ck_imbalance_dominant'),
    sa.CheckConstraint("kapha_state IN ('normal','increased','decreased')", name='ck_imbalance_kapha_state'),
    sa.CheckConstraint("pitta_state IN ('normal','increased','decreased')", name='ck_imbalance_pitta_state'),
    sa.CheckConstraint("vata_state IN ('normal','increased','decreased')", name='ck_imbalance_vata_state'),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imbalance_assessment_visit_id'), 'imbalance_assessment', ['visit_id'], unique=True)
    op.create_table('patient_assessment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=False),
    sa.Column('citation_id', sa.String(length=64), nullable=False),
    sa.Column('prakriti', sa.String(length=10), nullable=False),
    sa.Column('vikriti', sa.String(length=10), nullable=False),
    sa.Column('sara', sa.String(length=10), nullable=False),
    sa.Column('samhanana', sa.String(length=10), nullable=False),
    sa.Column('satmya', sa.String(length=10), nullable=False),
    sa.Column('satva', sa.String(length=10), nullable=False),
    sa.Column('ahara_shakti', sa.String(length=10), nullable=False),
    sa.Column('vyayama_shakti', sa.String(length=10), nullable=False),
    sa.Column('vaya', sa.String(length=10), nullable=False),
    sa.Column('pramana', sa.String(length=10), nullable=False),
    sa.Column('strength_score', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.String(length=30), server_default='now()', nullable=False),
    sa.CheckConstraint("ahara_shakti IN ('strong','moderate','weak')", name='ck_pa_ahara_shakti'),
    sa.CheckConstraint("prakriti IN ('strong','moderate','weak')", name='ck_pa_prakriti'),
    sa.CheckConstraint("pramana IN ('strong','moderate','weak')", name='ck_pa_pramana'),
    sa.CheckConstraint("samhanana IN ('strong','moderate','weak')", name='ck_pa_samhanana'),
    sa.CheckConstraint("sara IN ('strong','moderate','weak')", name='ck_pa_sara'),
    sa.CheckConstraint("satmya IN ('strong','moderate','weak')", name='ck_pa_satmya'),
    sa.CheckConstraint("satva IN ('strong','moderate','weak')", name='ck_pa_satva'),
    sa.CheckConstraint("vaya IN ('strong','moderate','weak')", name='ck_pa_vaya'),
    sa.CheckConstraint("vikriti IN ('strong','moderate','weak')", name='ck_pa_vikriti'),
    sa.CheckConstraint("vyayama_shakti IN ('strong','moderate','weak')", name='ck_pa_vyayama_shakti'),
    sa.ForeignKeyConstraint(['citation_id'], ['citation.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_assessment_visit_id'), 'patient_assessment', ['visit_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_assessment_visit_id'), table_name='patient_assessment')
    op.drop_table('patient_assessment')
    op.drop_index(op.f('ix_imbalance_assessment_visit_id'), table_name='imbalance_assessment')
    op.drop_table('imbalance_assessment')
    op.drop_index(op.f('ix_finding_code_who_tm_code'), table_name='finding_code')
    op.drop_index(op.f('ix_finding_code_visit_id'), table_name='finding_code')
    op.drop_index(op.f('ix_finding_code_national_code'), table_name='finding_code')
    op.drop_table('finding_code')
    op.drop_index(op.f('ix_disease_analysis_visit_id'), table_name='disease_analysis')
    op.drop_table('disease_analysis')
    op.drop_index(op.f('ix_dictation_visit_id'), table_name='dictation')
    op.drop_table('dictation')
    op.drop_index(op.f('ix_constitution_response_assessment_id'), table_name='constitution_response')
    op.drop_table('constitution_response')
    op.drop_index(op.f('ix_clinical_exam_visit_id'), table_name='clinical_exam')
    op.drop_table('clinical_exam')
    op.drop_index(op.f('ix_visit_practitioner_id'), table_name='visit')
    op.drop_index(op.f('ix_visit_patient_id'), table_name='visit')
    op.drop_table('visit')
    op.drop_index(op.f('ix_constitution_assessment_patient_id'), table_name='constitution_assessment')
    op.drop_table('constitution_assessment')
    op.drop_index(op.f('ix_terminology_code'), table_name='terminology')
    op.drop_table('terminology')
    op.drop_index(op.f('ix_patient_health_id'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_citation_rule_id'), table_name='citation')
    op.drop_table('citation')
    # ### end Alembic commands ###
